version: '3.9'

services:
  db:
    image: postgres:16
    container_name: teamweave-db
    environment:
      POSTGRES_DB: teamweave
      POSTGRES_USER: teamweave
      POSTGRES_PASSWORD: teamweave
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
